name: Upload to steam workshop
on:
  push:
    branches:
    - '*'


jobs:
  steam-workshop-upload:
    runs-on: ubuntu-latest
    steps:
      - name: steam-workshop-upload
        uses: Weilbyte/steam-workshop-upload@v1.1
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }} 
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}